[owo] Update build gradle info with arch fixes and common setup
wisp-forest/docs pull request #21
Opened 2024-11-02 23:35 UTC by Dragon-Seeker

2025-04-13 12:57 UTC, Noaaan requested changes
Found out why this doesn't quite work, added some notes on small improvements.

Should we also specify that you also need to add the repository for Sinytra (due to FFAPI)? This is a required dep for owo-lib-neoforge

2025-04-13 12:57 UTC, Noaaan commented on docs/owo/setup.md
> +        // Vanilla/Moddev Projects - Neoforge
What does vanilla mean in this regard? If it refers to ModDevGradles Vanilla-Mode, then it should probably be specified like so:
```diff
+ // ModDevGradle (including Vanilla-Mode) - NeoForge

2025-04-13 12:57 UTC, Noaaan commented on docs/owo/setup.md
> +        // Required due to issues with Arch Loom and JIJ within neo. May require bumping the version every once and awhile.
Is the case still that Arch Loom requires manually including these?

2025-04-13 12:57 UTC, Noaaan commented on docs/owo/setup.md
>          accessTransformer "io.wispforest:owo-lib-neoforge:${project.owo_version}"
```suggestion
        accessTransformers "io.wispforest:owo-lib-neoforge:${project.owo_version}"
```

2025-04-14 06:04 UTC, Dragon-Seeker commented on docs/owo/setup.md
>          accessTransformer "io.wispforest:owo-lib-neoforge:${project.owo_version}"
@Noaaan Are you sure as the Mod dev README states otherwise: https://github.com/neoforged/ModDevGradle/blob/12c58a2a8f8fbf03552fe1c7a215ffbd2dd6bcc2/README.md?plain=1#L531

2025-04-14 06:05 UTC, Dragon-Seeker commented on docs/owo/setup.md
> +        // Required due to issues with Arch Loom and JIJ within neo. May require bumping the version every once and awhile.
Yes as I attempted to ask about it but not much discussion about such took place and overall development seems kinda staled/inactive

2025-04-14 06:08 UTC, Dragon-Seeker commented on docs/owo/setup.md
> +        // Vanilla/Moddev Projects - Neoforge
I think it refers to such but there is also [VanillaGradle](https://github.com/SpongePowered/VanillaGradle) so 🤷

2025-04-14 06:26 UTC, Noaaan commented on docs/owo/setup.md
> +        // Vanilla/Moddev Projects - Neoforge
I don't think that is something we can support, as owo-lib depends on FAPI/FFAPI

2025-04-14 06:26 UTC, Noaaan commented on docs/owo/setup.md
>          accessTransformer "io.wispforest:owo-lib-neoforge:${project.owo_version}"
I was not able to build it without the s. Users in Discord also experienced the same issue

2025-04-14 06:54 UTC, Noaaan commented on docs/owo/setup.md
> +        // Vanilla/Moddev Projects - Neoforge
Given my understanding this is in reference to something different, you get to decide on whether we change it. Either is fine :+1:

2025-05-12 07:53 UTC, merged